name: Rust Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Rust Release
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: release
